### PR TITLE
polishes a few items.

### PR DESCRIPTION
**Pull request by dabjulmaros**
Adds round() width to the dynamic backgrounds. It already works in firefox, as soon as other browsers adobt it will allow for pixel perfect backgronds.

### CODE REVIEW

**Review by chinnuu05 — APPROVED** [review]

**Comment by chinnuu05** [comment]
thanks, how exactly did you find this repo? lol

**Comment by dabjulmaros** [comment]
I found the github user from the link in the page. The https://github.com/chinnuu05/notionwidgets one. Its broken to the public btw, its either private or the repo was deleted. I was gonna comment about that before but i forgot lol.

**Comment by chinnuu05** [comment]
> I found the github user from the link in the page. The https://github.com/chinnuu05/notionwidgets one. Its broken to the public btw, its either private or the repo was deleted. I was gonna comment about that before but i forgot lol.

Oh lol. Your code breaks responsiveness on mobile, the margin top gets removed hiding the landing page text on some screens

**Comment by dabjulmaros** [comment]
whats screens? I was sure i tested it on all of them

**Pull request merged**
